# For UART used from main().
CONFIG_RING_BUFFER=y
CONFIG_UART_CONSOLE=n
CONFIG_UART_INTERRUPT_DRIVEN=y

# For TVMPlatformAbort().
CONFIG_REBOOT=y

# For RPC server C++ bindings.
CONFIG_CPLUSPLUS=y
CONFIG_LIB_CPLUSPLUS=y

# For math routines
CONFIG_NEWLIB_LIBC=y

# For random number generation.
CONFIG_TEST_RANDOM_GENERATOR=y

# Extra prj.conf directives

